return {
	"xiyaowong/nvim-transparent",
	lazy = false,
	opts = {
		groups = {
			"Normal",
			"NormalNC",
			"Comment",
			"Constant",
			"Special",
			"Identifier",
			"Statement",
			"PreProc",
			"Type",
			"Underlined",
			"Todo",
			"String",
			"Function",
			"Conditional",
			"Repeat",
			"Operator",
			"Structure",
			"LineNr",
			"NonText",
			"SignColumn",
			"StatusLine",
			"StatusLineNC",
			"EndOfBuffer",
		},
		-- table: additional groups that should be cleared
		extra_groups = {
			"NormalFloat",
			"NvimTreeNormal",
			"NvimTreeNormalNC",
			"NvimTreeNormalFloat",
			"NvimTreeEndOfBuffer",
			"StatusLine",
			"StatusLineNC",
			"BufferLineTabClose",
			"BufferlineBufferSelected",
			"BufferLineFill",
			"BufferLineBackground",
			"BufferLineSeparator",
			"BufferLineIndicatorSelected",

			"IndentBlanklineChar",

			-- make floating windows transparent
			"LspFloatWinNormal",
			"Normal",
			"NormalFloat",
			"FloatBorder",
			"TelescopeNormal",
			"TelescopeBorder",
			"TelescopePromptBorder",
			"SagaBorder",
			"SagaNormal",
		},
	},
}
